import { Theme } from "../theme.slint";

export component Slider {
    in property <Orientation> orientation: Orientation.horizontal;
    in property <float> minimum: 0;
    in property <float> maximum: 100;
    in property <float> step: 1;
    in property <bool> enabled: true;
    in-out property <float> value: root.minimum;
    out property <bool> has-focus: i-focus-scope.has-focus;

    callback changed(float);
    callback released(float);

    out property <bool> vertical: root.orientation == Orientation.vertical;
    private property <length> thumb-size: 16px;

    pure function size-to-value(size: length, range: length) -> float {
        size * (root.maximum - root.minimum) / range;
    }

    public function set-value(v: float) {
        root.value = max(root.minimum, min(root.maximum, v));
        root.changed(root.value);
    }

    public function increment() {
        root.set-value(root.value + root.step);
    }

    public function decrement() {
        root.set-value(root.value - root.step);
    }

    min-width: root.vertical ? root.thumb-size : 0px;
    min-height: root.vertical ? 0px : root.thumb-size;
    horizontal-stretch: root.vertical ? 0 : 1;
    vertical-stretch: root.vertical ? 1 : 0;
    forward-focus: i-focus-scope;

    states [
        disabled when !root.enabled : {
            i-track.background: Theme.muted-foreground;
            i-thumb.background: Theme.muted-foreground;
        }
    ]

    i-rail := Rectangle {
        x: root.vertical ? (parent.width - self.width) / 2 : 0px;
        y: root.vertical ? 0px : (parent.height - self.height) / 2;
        width: root.vertical ? 4px : 100%;
        height: root.vertical ? 100% : 4px;
        border-radius: 2px;
        background: Theme.secondary;
    }

    i-track := Rectangle {
        x: i-rail.x;
        y: root.vertical ? i-thumb.y + i-thumb.height / 2 : i-rail.y;
        width: root.vertical ? i-rail.width : i-thumb.x + i-thumb.width / 2;
        height: root.vertical ? i-rail.height - i-thumb.y - i-thumb.height / 2 : i-rail.height;
        border-radius: i-rail.border-radius;
        background: Theme.primary;
    }

    i-thumb := Rectangle {
        x: root.vertical ? (parent.width - self.width) / 2 : clamp((parent.width - self.width) * (root.value - root.minimum) / (root.maximum - root.minimum), 0px, parent.width - self.width);
        y: root.vertical ? clamp((parent.height - self.height) * (root.maximum - root.value) / (root.maximum - root.minimum), 0px, parent.height - self.height) : (parent.height - self.height) / 2;
        width: root.thumb-size;
        height: root.thumb-size;
        border-radius: self.width / 2;
        background: Theme.background;
        border-width: 2px;
        border-color: Theme.primary;

        if root.has-focus && root.enabled : Rectangle {
            x: -2px;
            y: -2px;
            width: parent.width + 4px;
            height: parent.height + 4px;
            border-radius: parent.border-radius + 2px;
            border-width: 2px;
            border-color: Theme.ring;
        }
    }

    i-touch-area := TouchArea {
        property <float> pressed-value;
        enabled: root.enabled;
        width: 100%;
        height: 100%;

        pointer-event(event) => {
            if (event.button != PointerEventButton.left) {
                return;
            }
            if (event.kind == PointerEventKind.up) {
                root.released(root.value);
                return;
            }
            self.pressed-value = root.value;
            i-focus-scope.focus();
        }

        moved => {
            if (!self.enabled) {
                return;
            }
            root.set-value(self.pressed-value + (!root.vertical
                ? root.size-to-value(self.mouse-x - self.pressed-x, root.width - root.thumb-size)
                : root.size-to-value(self.pressed-y - self.mouse-y, root.height - root.thumb-size)));
        }
    }

    i-focus-scope := FocusScope {
        x: 0;
        width: 0px;
        enabled: root.enabled;

        key-pressed(event) => {
            if (root.step <= 0) {
                return reject;
            }
            if ((!root.vertical && event.text == Key.RightArrow) || (root.vertical && event.text == Key.UpArrow)) {
                root.increment();
                return accept;
            } else if ((!root.vertical && event.text == Key.LeftArrow) || (root.vertical && event.text == Key.DownArrow)) {
                root.decrement();
                return accept;
            }
            return reject;
        }
    }
}
