[package]
name = "corona_shell"
version = "0.1.0"
edition = "2024"

[dependencies]
regex.workspace = true
clap.workspace = true
corona_surface.workspace = true
corona_components.workspace = true
corona_compositor.workspace = true
corona_pipewire.workspace = true
corona_desktop.workspace = true
corona_network_manager.workspace = true
corona_mpris.workspace = true
corona_bluez.workspace = true
corona_power.workspace = true
corona_brightness.workspace = true
corona_notifications.workspace = true
corona_tray.workspace = true
corona_idle.workspace = true
corona_auth.workspace = true
corona_auth_screen.workspace = true
corona_sysinfo.workspace = true
corona_weather.workspace = true
corona_script.workspace = true
corona_utils.workspace = true
corona_config.workspace = true
corona_ipc.workspace = true
corona_capture.workspace = true
gpui-kit.workspace = true
uuid.workspace = true
anyhow.workspace = true
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
zbus.workspace = true
futures.workspace = true
tracing.workspace = true
jiff = "0.2.37"
rust-i18n.workspace = true
jiff-icu = { version = "0.2.2", default-features = false, features = ["std", "time"] }
icu_calendar = "2.3"
icu_datetime = "2.3"
icu_decimal = "2.3"
icu_locale = "2.3"
rodio = { git = "https://github.com/RustAudio/rodio", rev = "685e05765c2aff8fbb51e32cda5b18428d09ffbe", default-features = false, features = [
  "playback",
  "vorbis",
  "pipewire",
] }

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
tempfile.workspace = true
