[package]
name = "corona_config"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui-kit.workspace = true
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
dirs.workspace = true
glob.workspace = true
flume.workspace = true
tracing.workspace = true
notify = "8.2.0"
serde_ignored = "0.1.14"
toml = "1.1.6"
config = { version = "0.15.26", default-features = false, features = ["toml"] }
