[package]
name = "corona_script"
version = "0.1.0"
edition = "2024"

[dependencies]
corona_config = { workspace = true }
corona_macros = { workspace = true }
corona_compositor = { workspace = true }
corona_pipewire = { workspace = true }
corona_utils = { workspace = true }
gpui-kit = { workspace = true }
gpui-shell = { workspace = true }
gpui-component-shell = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
dirs = { workspace = true }
ts-rs = { workspace = true }
schemars = "1.2.2"
