[package]
name = "corona_capture"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui-kit.workspace = true
anyhow.workspace = true
image = { version = "0.25.10", default-features = false, features = ["png"] }
futures.workspace = true
gbm = { version = "0.18.0", default-features = false }
gpui_wgpu = { package = "gpui-pre-wgpu", version = "0.3.7" }
tracing.workspace = true
rustix = { workspace = true, features = ["fs"] }
wayland-client.workspace = true
wayland-backend.workspace = true
wayland-scanner.workspace = true
wayland-protocols-wlr.workspace = true
wayland-protocols.workspace = true

[dev-dependencies]
gpui-kit = { workspace = true, features = ["test-support"] }
