[package]
name = "corona_reqwest"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest_client = { package = "gpui-pre-reqwest-client", version = "=0.3.7" }
http_client = { package = "gpui-pre-http-client", version = "=0.3.7" }
futures = "0.3"
anyhow.workspace = true
serde.workspace = true
serde_json.workspace = true
tracing.workspace = true
dirs.workspace = true
