[package]
name = "corona_notifications"
version = "0.1.0"
edition = "2024"

[dependencies]
corona_utils.workspace = true
corona_config.workspace = true
gpui-kit.workspace = true
zbus.workspace = true
anyhow.workspace = true
flume.workspace = true
futures-lite.workspace = true
tracing.workspace = true
dirs.workspace = true
image = { version = "0.25.10", default-features = false, features = ["png"] }

[dev-dependencies]
corona_utils = { workspace = true, features = ["test-support"] }
gpui-kit = { workspace = true, features = ["test-support"] }
