import { Button } from "std-widgets.slint";

export component Bar inherits Window {
  callback clicked();
  in property <[string]> workspaces: [];

  background: #ffffff;

  HorizontalLayout {
  alignment: space-between;
  Button {
    text: "Click Me";
    width: 100px;

    clicked => {
      clicked();
    }
  }

  HorizontalLayout {
  for workspace[i] in workspaces: Button {
    width: 20px;
    text: workspace;
  }
  }

  TextInput {
  width: 200px;
  color: #000000;
  }
  }
}
