component Button inherits Rectangle {
    in-out property text <=> txt.text;
    callback clicked <=> touch.clicked;
    border-radius: root.height / 2;
    border-width: 1px;
    border-color: root.background.darker(25%);
    background: touch.pressed ? #6b8282 : touch.has-hover ? #6c616c :  #456;
    height: txt.preferred-height * 1.8;
    min-width: txt.preferred-width + 20px;
    txt := Text {
        x: (parent.width - self.width)/2;
        y: (parent.height - self.height)/2;
        color: touch.pressed ? #fff : #eee;
    }
    touch := TouchArea { }
}

export component Bar inherits Window {
  callback clicked();
  callback workspaceClicked(workspace: string);
  in property <[string]> workspaces: [];

  background: #ffffff;

  HorizontalLayout {
  alignment: space-between;
  Button {
    text: "Click Me";
    width: 100px;

    clicked => {
      clicked();
    }
  }

  HorizontalLayout {
  for workspace[i] in workspaces:
  Button {
    width: 30px;
    text: workspace;
    clicked => {
      workspaceClicked(workspace);
    }
  }
  }

  TextInput {
  width: 200px;
  color: #000000;
  }
  }
}
