import { Button } from "components/button.slint";

export component Panel inherits Window {
  in property <duration> anim-duration: 300ms;

  callback clicked();
  callback closed();

  default-font-family: "Geist";

  private property <length> self_height: 0px;
  animate self_height {
    duration: root.anim-duration;
    easing: ease-out-quad;
  }

  background: transparent;

  public function toggle_open() {
    if (close-timer.running) {
      close-timer.stop();
      root.self_height = root.height;
    } else if (root.self_height > 0px) {
      root.self_height = 0px;
      close-timer.start();
    } else {
      root.self_height = root.height;
    }
  }

  init => {
    root.self_height = root.height;
  }

  close-timer := Timer {
    interval: root.anim-duration;
    running: false;
    triggered => {
      close-timer.stop();
      root.closed();
    }
  }

  Rectangle {
    y: 0;
    width: 100%;
    height: root.self_height;
    background: #ff0fff;
    clip: true;

    Button {
      text: "Click Me";
      width: 100px;

      clicked => {
        clicked();
      }
    }
  }
}
