[package]
name = "corona_power"
version = "0.1.0"
edition = "2024"

[dependencies]
corona_utils.workspace = true
gpui-kit.workspace = true
zbus.workspace = true
anyhow.workspace = true
futures-lite.workspace = true
corona-zbus-upower = "0.1.0"

[dev-dependencies]
corona_utils = { workspace = true, features = ["test-support"] }
gpui-kit = { workspace = true, features = ["test-support"] }
flume.workspace = true
